version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: make build
      - run: make test
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: make build
      - run: echo "TODO add publishing"
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
