version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.5-node
    steps:
      - checkout
      - run: make install
      - run: make build
      - run: make test
  publish-website:
    docker:
      - image: circleci/ruby:2.4.5-node
    steps:
      - checkout
      - run: make install
      - run: make build
      - run: make publish-website
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish-website:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
