
name: Build and deploy the Google Sheets

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '^22.13'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run the tests
        run: npm test
      - name: Deploy the google sheets
        run: node ./scripts/deploy-google-sheets.js
        env:
          SERVICE_ACCOUNT_KEYFILE: ${{ secrets.SERVICE_ACCOUNT_KEYFILE }}
          VERSION: ${{ github.ref_name }}
